
version: '3'


tasks:
  publish:
    cmds:
      - pip install wheel
      - python -m pip install --upgrade build
      - python  -m build
      - python  -m pip install --upgrade twine
      - python  -m twine upload --repository pypi dist/*
